#!/usr/bin/env bash

mv "$HOME/.vimrc" "$HOME/.vimrc.orig" 2>/dev/null
sudo mv "/root/.vimrc" "/root/.vimrc.orig" 2>/dev/null
cp "$(pwd)/dot_vimrc" "$HOME/.vimrc"
sudo cp "$(pwd)/dot_vimrc" "/root/.vimrc"
